# Welcome to Jekyll!
#
# Site settings
# Personalize your new site. Variables like {{ site.title }}, {{ site.email }},
# and others will be available throughout your templates.

#title: eiplgrader
#make title an image
title: eiplgrader
logo: "/assets/images/eiplgrader.png"
email: dhsmith2@illinois.edu
description: >- # Ignore newlines until "baseurl:"
  This is a project to create an autograder for "Explain in Plain Language" questions. The goal is to provide students with immediate feedback on their answers to these questions, which are often used in computer science courses to assess students' understanding of complex topics.
baseurl: "" # Set the subpath for your site, e.g., /blog (leave blank if root).
url: "http://hamiltonfour.tech" # Base URL for your site.

# Build settings
theme: just-the-docs
search_enabled: false
heading_anchors: true
color_scheme: "dark"
live_reload: true

aux_links:
  David H Smith IV: 'https://hamiltonfour.tech'

footer_content: "Powered by Jekyll and just-the-docs theme."

# Exclude these files and directories from the site build
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  - fixtures/

